package com.goto456.model;

import java.util.List;

import com.goto456.model.base.BaseBlogTags;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BlogTags extends BaseBlogTags<BlogTags> {
	public static final BlogTags dao = new BlogTags();
	
	/**
	 * 
	 * @return
	 */
	public static List<Record> queryCount(){
		String sql = "select tagName,count(tagID) as blogNum from blog_tags_display group by tagID";
		return Db.find(sql);
	}
}
