package com.goto456.model;

import com.goto456.model.base.BaseTimeline;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Timeline extends BaseTimeline<Timeline> {
	public static final Timeline dao = new Timeline();
}
